/**
 * NetSuite Stock Lens
 * Copyright (c) 2026 Fabian Rodriguez
 * Licensed under the MIT License. See LICENSE in the project root.
 */
import { defineConfig } from "wxt";

// WXT framework configuration. Source maps are disabled so the distributed
// bundle does not leak original source structure to end users.
export default defineConfig({
  srcDir: "src",
  modules: ["@wxt-dev/module-react"],
  manifest: {
    name: "NetSuite Stock Lens",
    // Listed in the Chrome Web Store summary. Keep under 132 chars.
    description:
      "Show live NetSuite inventory (on hand, committed, available, on order, by location) on hover inside transactions.",
    // Explicit declaration so the manifest is unambiguous even if WXT's
    // auto-discovery from public/icon/ changes across versions.
    icons: {
      16: "icon/16.png",
      32: "icon/32.png",
      48: "icon/48.png",
      128: "icon/128.png",
    },
    action: {
      default_title: "NetSuite Stock Lens",
      default_icon: {
        16: "icon/16.png",
        32: "icon/32.png",
        48: "icon/48.png",
        128: "icon/128.png",
      },
    },
    permissions: ["storage"],
    host_permissions: ["*://*.netsuite.com/*", "*://*.app.netsuite.com/*", "*://*.suiteapp.com/*"],
    web_accessible_resources: [
      {
        // The page-context bridge is emitted as `/injected.js` because WXT
        // unlisted scripts use the entrypoint folder name as the basename.
        resources: ["injected.js"],
        matches: ["*://*.netsuite.com/*", "*://*.app.netsuite.com/*", "*://*.suiteapp.com/*"],
      },
    ],
    // `options_ui` is generated by WXT from the options entrypoint metadata.
    // `open_in_tab` is set via the `manifest.open_in_tab` meta tag inside
    // `src/entrypoints/options/index.html`.
  },
  vite: () => ({
    build: {
      sourcemap: false,
    },
  }),
});
